import type { McpServerDefinition, McpTransport } from "./types.js";

export function buildClientConfig(
  name: string,
  transport: McpTransport,
  serverId: string,
): Record<string, unknown> {
  if (transport === "http") {
    return {
      mcpServers: {
        [name]: {
          url: `https://api.devibe.app/mcp/${serverId}`,
          transport: "http",
        },
      },
    };
  }
  return {
    mcpServers: {
      [name]: {
        command: "npx",
        args: ["-y", "@devibe/mcp-server", "--server-id", serverId],
        env: {
          DEVIBE_MOCK_CLOUD: "true",
        },
      },
    },
  };
}

export function buildBootstrapTs(def: Pick<McpServerDefinition, "name" | "plugins" | "tools" | "cloud">): string {
  const toolNames = def.tools.map((t) => t.name);
  return `/**
 * Generated by Monaco Cloud MCP Server Builder
 * Server: ${def.name}
 * Plugins: ${def.plugins.join(", ")}
 */
import { createMcpServer } from "@devibe/mcp-server";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";

async function main() {
  const server = createMcpServer({
    name: ${JSON.stringify(def.name)},
    plugins: ${JSON.stringify(def.plugins)},
    cloud: ${JSON.stringify(def.cloud ?? null)},
  });
  // Registered tools: ${toolNames.join(", ")}
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
`;
}

export type McpSdkLanguage = "typescript" | "python" | "go" | "rust" | "nodejs";

/** Multi-language MCP SDK starter templates for Marketplace / Builder. */
export function buildLanguageTemplate(
  language: McpSdkLanguage,
  name: string,
): string {
  switch (language) {
    case "python":
      return `"""Monaco Cloud MCP server — ${name} (Python SDK template)"""\nfrom mcp.server.fastmcp import FastMCP\n\nmcp = FastMCP(${JSON.stringify(name)})\n\n@mcp.tool()\ndef health() -> str:\n    return "ok"\n\nif __name__ == "__main__":\n    mcp.run()\n`;
    case "go":
      return `// Monaco Cloud MCP server — ${name} (Go SDK template)\npackage main\n\nfunc main() {\n  // TODO: wire MCP SDK + Universal capabilities\n}\n`;
    case "rust":
      return `// Monaco Cloud MCP server — ${name} (Rust SDK template)\nfn main() {\n    // TODO: wire rmcp / MCP SDK + Universal capabilities\n}\n`;
    case "nodejs":
      return `/** Monaco Cloud MCP server — ${name} (Node.js CJS template) */\nconst { createMcpServer } = require("@devibe/mcp-server");\nmodule.exports = { createMcpServer };\n`;
    default:
      return buildBootstrapTs({ name, plugins: ["cloud"], tools: [], cloud: undefined });
  }
}

