import type { McpServerDefinition, McpTransport } from "./types.js";

export function buildClientConfig(
  name: string,
  transport: McpTransport,
  serverId: string,
): Record<string, unknown> {
  if (transport === "http") {
    return {
      mcpServers: {
        [name]: {
          url: `https://api.devibe.app/mcp/${serverId}`,
          transport: "http",
        },
      },
    };
  }
  return {
    mcpServers: {
      [name]: {
        command: "npx",
        args: ["-y", "@devibe/mcp-server", "--server-id", serverId],
        env: {
          DEVIBE_MOCK_CLOUD: "true",
        },
      },
    },
  };
}

export function buildBootstrapTs(def: Pick<McpServerDefinition, "name" | "plugins" | "tools" | "cloud">): string {
  const toolNames = def.tools.map((t) => t.name);
  return `/**
 * Generated by DeVibe MCP Server Builder
 * Server: ${def.name}
 * Plugins: ${def.plugins.join(", ")}
 */
import { createMcpServer } from "@devibe/mcp-server";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";

async function main() {
  const server = createMcpServer({
    name: ${JSON.stringify(def.name)},
    plugins: ${JSON.stringify(def.plugins)},
    cloud: ${JSON.stringify(def.cloud ?? null)},
  });
  // Registered tools: ${toolNames.join(", ")}
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
`;
}
